### ISSUE TITLE
Cannot find name 'ITelemetryLogger when upgrading to fluid 0.41.0 from 0.33.5

### ISSUE THREAD

**Issue by deraldop** [microsoft/FluidFramework#6695]
Cannot find name 'ITelemetryLogger when upgrading to fluid 0.41.0 from 0.33.5

As part of the process I started using @fluid-experimental/get-container instead of @fluidframework/get-tinylicious-container

ERROR in node_modules/@fluid-experimental/get-container/node_modules/@fluidframework/routerlicious-driver/dist/documentStorageService.d.ts:5:15 - error TS2304: Cannot find name 'ITelemetryLogger'.
[0]     
[0]     5 import type { ITelemetryLogger } from "@fluidframework/common-definitions";

Not sure how you'd be able to Reproduce, but it breaks my build.

I tracked it down to node_modules and it seems "@fluidframework/common-definitions" is _phantomChildren and for some reason the ITelemetryLogger cannot be found

**Comment by tylerbutler** [comment]
@deraldop There were a number of breaking changes vbetween 0.33.5 and 0.41.0. See https://github.com/microsoft/FluidFramework/blob/main/BREAKING.md for the details. From a quick look it does seem like there were changes to ITelemetryLogger and related types. Can you share your full package.json?

**Comment by deraldop** [comment]
sure,

{
  "name": "gis-app",
  "version": "1.0.0",
  "description": "Web client...",
  "scripts": {},
  "husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged"
    }
  },
  "dependencies": {
    "@angular/cdk": "9.2.0",
    "@angular/flex-layout": "9.0.0-beta.29",
    "@fluidframework/aqueduct": "^0.33.5",
    "@fluidframework/get-tinylicious-container": "^0.33.5",
    "@fluidframework/map": "^0.33.5",
    "@ng-select/ng-select": "4.0.0",
    "@ngneat/until-destroy": "8.0.3",
    "angular-d3-tree": "1.0.2",
    "body-parser": "1.19.0",
    "concurrently": "4.1.1",
    "cpr": "3.0.1",
    "d3": "5.15.1",
    "dnd-core": "10.0.2",
    "express": "4.17.1",
    "express-http-proxy": "1.5.1",
    "husky": "2.2.0",
    "jsrsasign-reduced": "^8.0.15",
    "jwt-decode": "2.2.0",
    "ngx-infinite-scroll": "9.0.0",
    "prettier": "1.17.1",
    "pretty-quick": "1.10.0",
    "request": "2.88.0",
    "tinylicious": "0.4.21640",
    "tslib": "1.11.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.901.7",
    "@angular-devkit/build-ng-packagr": "0.901.3",
    "@angular-devkit/core": "9.1.0",
    "@angular-devkit/schematics": "9.1.0",
    "@angular-extensions/lint-rules": "1.2.1",
    "@angular-skyhook/core": "1.3.3",
    "@angular/animations": "9.1.0",
    "@angular/cdk": "9.2.0",
    "@angular/cli": "9.1.0",
    "@angular/common": "9.1.0",
    "@angular/compiler": "9.1.0",
    "@angular/compiler-cli": "9.1.0",
    "@angular/core": "9.1.0",
    "@angular/forms": "9.1.0",
    "@angular/language-service": "9.1.0",
    "@angular/material": "9.2.0",
    "@angular/material-moment-adapter": "9.2.0",
    "@angular/platform-browser": "9.1.0",
    "@angular/platform-browser-dynamic": "9.1.0",
    "@angular/router": "9.1.0",
    "@ngrx/effects": "9.1.2",
    "@ngrx/schematics": "9.1.2",
    "@ngrx/store": "9.1.2",
    "@ngrx/store-devtools": "9.1.2",
    "@types/async": "2.0.49",
    "@types/geojson": "7946.0.7",
    "@types/googlemaps": "3.39.11",
    "@types/jasmine": "3.3.7",
    "@types/lodash": "4.14.136",
    "@types/node": "14.0.4",
    "@types/qunit": "2.9.0",
    "angular-auth-oidc-client": "9.0.8",
    "angularx-flatpickr": "6.1.0",
    "async": "2.6.1",
    "body-parser": "1.19.0",
    "chart.js": "2.9.3",
    "classlist.js": "1.1.20150312",
    "codelyzer": "5.0.1",
    "core-js": "3.1.0",
    "flatpickr": "4.5.2",
    "gulp": "4.0.2",
    "gulp-clean": "0.4.0",
    "gulp-connect": "5.7.0",
    "gulp-replace": "1.0.0",
    "gulp-sass": "4.0.2",
    "gulp-shell": "0.8.0",
    "gulp-typescript": "5.0.1",
    "hammerjs": "2.0.8",
    "http-server": "0.12.3",
    "jasmine-core": "3.5.0",
    "jasmine-reporters": "2.3.2",
    "jasmine-spec-reporter": "5.0.2",
    "jwt-decode": "2.2.0",
    "karma": "5.0.4",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "3.0.2",
    "karma-jasmine": "3.1.1",
    "karma-jasmine-html-reporter": "1.5.3",
    "karma-junit-reporter": "2.0.1",
    "karma-mocha-reporter": "2.2.5",
    "lodash": "4.17.20",
    "ng-packagr": "9.1.5",
    "ngx-cookie": "4.0.2",
    "ngx-md": "8.1.6",
    "ngx-webstorage": "3.0.0-beta.14",
    "node-sass": "4.11.0",
    "npm-scripts-info": "0.3.9",
    "omni-slider": "1.2.1",
    "pikaday": "1.7.0",
    "protractor": "7.0.0",
    "protractor-image-comparison": "2.0.1",
    "puppeteer": "5.5.0",
    "react-dnd-html5-backend": "9.4.0",
    "react-dnd-test-backend": "9.4.0",
    "request": "2.88.0",
    "require": "2.4.20",
    "rimraf": "2.6.3",
    "ruru-protractor-junit-reporter": "0.0.1",
    "rxjs": "6.5.4",
    "rxjs-tslint": "0.1.8",
    "socket.io-client": "2.2.0",
    "taggle": "1.14.0",
    "ts-node": "5.0.1",
    "tsickle": "0.35.0",
    "tslint": "5.12.1",
    "tslint-config-prettier": "1.18.0",
    "typescript": "3.7.5",
    "webpack": "^4.46.0",
    "webpack-cli": "^4.2.0",
    "webpack-dev-server": "^3.11.2",
    "webpack-merge": "^5.4.1",
    "zone.js": "0.10.3"
  }
}

**Comment by deraldop** [comment]
I first thought this was due to the lack of "common-definitions" from routerlicious-driver node_modules. Not sure anymore this is the case, since that didn't seem to make a difference

**Comment by deraldop** [comment]
nevermind, I had my typescript at 3.7.5 and "import type" started at 3.8. please close this.
