### ISSUE TITLE
some ideas about benchmark tool

### ISSUE THREAD

**Issue by blindperson** [microsoft/FluidFramework#10068]
## Feature
 - when I use `@fluid-tools/benchmark` dependence, the latest version is  0.40.27919, but this version don't have [this](https://github.com/microsoft/FluidFramework/pull/7048) change. Can you help publish new version containing this PR，thx
 -  tools/benchmark doesn't support mocha 9, can you help upgrade mocha?
https://github.com/microsoft/FluidFramework/blob/c458824d0bd71ddac9033ef7ec08254d938da802/tools/benchmark/package.json#L3

**Comment by blindperson** [comment]
PS: In our project I found some errors when I try to generate benchmark report. And I think it is relate to mocha V9.2.2.

```
Test Uncaught error outside test suite failed with error: 'test.on is not a function'

Overall summary

suite name  geometric mean (ns)  # of passed tests  total time (s)
----------  -------------------  -----------------  --------------
total                       NaN         0 out of 0             0.0

Test Uncaught error outside test suite failed with error: 'test.on is not a function'
Test Uncaught error outside test suite failed with error: 'test.on is not a function'
```

**Comment by alexvy86** [comment]
@blindperson are you still encountering those errors with the latest version of `@fluid-tools/benchmark` (`0.43.90439`, which I just noticed is marked as canary and not latest, but it is in fact the latest so it's safe to use)? I expect the first bullet point should now be addressed after [this discussion](https://github.com/microsoft/FluidFramework/pull/11184).

**Comment by blindperson** [comment]
@alexvy86 oh, there's no problem! After updating to 0.43, we can run as we expect, thank you very much for your team quick response and support! And we can close this issue.
