### PR TITLE
Revert "PropertyDDS: Summary generation Bug Fix"

### PR DESCRIPTION
**Pull request by jikim-msft**
Reverts microsoft/FluidFramework#18072

Internal `Build - client packages` failing with identical error after merging [18072](https://github.com/microsoft/FluidFramework/pull/18072)

Failed Task: `@***-experimental/property-dds: tsc --project ./src/test/tsconfig.json`
Error Log: `src/test/propertyTree.spec.ts:226:38 - error TS2304: Cannot find name 'requestFluidObject'.`

#### Subsequent Pipeline Failures
- [214310](https://dev.azure.com/fluidframework/internal/_build/results?buildId=214310&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=bfe27d5f-9219-57c0-0d67-1b2946a32921&l=923)
- [214366](https://dev.azure.com/fluidframework/internal/_build/results?buildId=214366&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=bfe27d5f-9219-57c0-0d67-1b2946a32921&l=922)
- [214405](https://dev.azure.com/fluidframework/internal/_build/results?buildId=214405&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=bfe27d5f-9219-57c0-0d67-1b2946a32921&l=927)

### CODE REVIEW

**Comment by jikim-msft** [comment]
Tagging @CraigMacomber @ruiterr @nedalhy for visibility.

**Review by anthony-murphy — APPROVED** [review]
please also add the error we are seeing to the description. not everyone will have acess to the internal builds.
